services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=toktok'
      - 'POSTGRES_PASSWORD=toktok'
      - 'POSTGRES_USER=toktok'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --requirepass toktok